services:
  - type: web
    name: bw-encuestas-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    preDeployCommand: python -m flask --app wsgi db upgrade
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: FLASK_ENV
        value: production
      - key: TIME_ZONE
        value: America/Mexico_City
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bw-encuestas-pro-db
          property: connectionString

      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Admin2002


databases:
  - name: bw-encuestas-pro-db
    plan: free
